# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

imports:
    - { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusShopBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminApiBundle/Resources/config/app/config.yml" }
    - { resource: "@ShopApiPlugin/Resources/config/app/config.yml" }

    - { resource: "parameters.yml" }
    - { resource: "security.yml" }

parameters:
    locale: en_US

framework:
    translator: { fallbacks: ["%locale%", "en"] }
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form: true
    csrf_protection: true
    validation: { enable_annotations: true }
    templating: { engines: ["twig"] }
    default_locale: "%locale%"
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler

doctrine:
    dbal:
        driver: "%database_driver%"
        host: "%database_host%"
        port: "%database_port%"
        dbname: "%database_name%"
        user: "%database_user%"
        password: "%database_password%"
        server_version: "5.5"
        charset: UTF8

doctrine_migrations:
    dir_name: "%kernel.root_dir%/migrations"
    namespace: Sylius\Migrations
    table_name: sylius_migrations
    name: Sylius Migrations

swiftmailer:
    transport: "%mailer_transport%"
    host: "%mailer_host%"
    port: "%mailer_port%"
    encryption: "%mailer_encryption%"
    auth_mode: "%mailer_auth_mode%"
    username: "%mailer_user%"
    password: "%mailer_password%"

fos_rest:
    exception: ~
    view:
        formats:
            json: true
            xml:  true
        empty_content: 204
    format_listener:
        rules:
            - { path: '^/shop-api', priorities: ['json'], fallback_format: json, prefer_extension: true }
            - { path: '^/api/.*', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: true }
            - { path: '^/', stop: true }

sylius_theme:
    sources:
        filesystem: ~

sylius_mailer:
    sender:
        name: "%mailer_sender_name%"
        address: "%mailer_sender_address%"

shop_api:
    auto_pickup_cart: true

sylius_shop:
    checkout_resolver:
        pattern: "%sylius.security.shop_regex%/checkout/.+"

lexik_jwt_authentication:
    private_key_path: '%jwt_private_key_path%'
    public_key_path:  '%jwt_public_key_path%'
    pass_phrase:      '%jwt_key_pass_phrase%'
    token_ttl:        '%jwt_token_ttl%'
    token_extractors:
        authorization_header:
            prefix: ~
            name: X-WX-Skey

fos_http_cache:
    cache_control:
        defaults:
            overwrite: true
        rules:
            # match all actions of a specific controller
            -
                match:
                    attributes: { _controller: sylius.shop_api_plugin.controller.product.show_latest_product_action }
                headers:
                    cache_control: { public: true, max_age: 64000, s_maxage: 64000 }
                    last_modified: "-1 hour"

# lilocon_wechat:

#     # Debug 模式，bool 值：true/false
#     # 当值为 false 时，所有的日志都不会记录
#     debug: "%kernel.debug%"

#     # 账号基本信息，请从微信公众平台/开放平台获取
#     app_id: "%wechat_app_id%"
#     secret: "%wechat_secret%"
#     token: "%wechat_token%"
#     aes_key: ""

#     # sdk缓存配置
#     cache:
#       overwrite: false # 是否使用自定义缓存
#       cache_id: wechat_cache # 自定义缓存service_id 若不填则使用easy_wechat默认缓存

#     # 防火墙配置
#     security:
#       enabled: false # 是否使用微信授权功能
#       user_provider_id: app_wechat_user_provider  # 用户提供者 service_id

orinoco_wechat:
    sandbox: "%wechat_sandbox%"
    applications:
        mini_program:
            app_id: "%wechat_mini_program_app_id%"
            secret: "%wechat_mini_program_secret%"
        payment:
            app_id: "%wechat_payment_app_id%"
            mch_id: "%wechat_payment_mch_id%"
            key: "%wechat_payment_key%"
