# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

shop_api_login_check:
    methods: [POST]
    path: /shop-api/login_check

sylius_shop_api:
    resource: "@ShopApiPlugin/Resources/config/routing.yml"

sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: /admin

sylius_admin_api:
    resource: "@SyliusAdminApiBundle/Resources/config/routing.yml"
    prefix: /api

sylius_shop:
    resource: "@SyliusShopBundle/Resources/config/routing.yml"
    prefix: /{_locale}
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

sylius_shop_payum:
    resource: "@SyliusShopBundle/Resources/config/routing/payum.yml"

sylius_shop_default_locale:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.shop.locale_switch:switchAction

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

spring:
    resource: "@NvidiaWeChatJSSDKBundle/Resources/config/routing.yml"
    prefix:   /spring

zshwag_wechat:
    resource: "@ZshwagWechatBundle/Resources/config/routing.xml"
    prefix:   /

zshwag_alipay:
    resource: "@ZshwagAlipayBundle/Resources/config/routing.xml"
    prefix:   /alipay

zshwag_static_page:
    resource: "@ZshwagStaticPageBundle/Resources/config/routing.xml"
    prefix:   /page
