<?php

namespace Zshwag\AlipayBundle\Repository;

/**
 * GatewayNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GatewayNotificationRepository extends \Doctrine\ORM\EntityRepository
{
}
